spring:
  data:
    mongodb:
      host: some-mongo
  jade4j:
    caching: false
    prettyPrint: true
api:
  hello:
    url: http://0.0.0.0:8080/api/hello/
    name: Me
    phrase: Hi
signal:
  url: some-api
  port: 8080
  #port: 5000
